context:
  name: orjson
  version: 3.10.18

package:
  name: ${{name}}
  version: ${{ version }}

source:
- url: https://files.pythonhosted.org/packages/source/o/orjson/orjson-${{ version }}.tar.gz
  sha256: e8da3947d92123eda795b68228cafe2724815621fe35e8e320a9e9593a4bcd53

build:
  number: 0

requirements:
  build:
  - cross-python_${{target_platform}}
  - cffi == 1.17.1
  - setuptools-rust
  - rust
  - maturin

  host:
  - python
  - openssl
  - cffi == 1.17.1
  run:
  - cffi == 1.17.1
  - typing_extensions

tests:
- script: pytester
  requirements:
    build:
    - pytester
    run:
    - pytester-run
  files:
    recipe:
    - test_orjson.py
