context:
  name: r-pillar
  version: 1.9.0
  r_base_version: 4.4.1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url:
    - https://cran.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
    - https://cloud.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
  sha256: f23eb486c087f864c2b4072d5cba01d5bebf2f554118bcba6886d8dbceb87acc

build:
  number: 0

requirements:
  build:
  - r-base == ${{ r_base_version }}
  host:
  - r-base == ${{ r_base_version }}
  - r-cli
  - r-crayon
  - r-ellipsis
  - r-fansi
  - r-lifecycle
  - r-rlang
  - r-utf8
  - r-vctrs
  run:
  - r-base == ${{ r_base_version }}
  - r-cli
  - r-crayon
  - r-ellipsis
  - r-fansi
  - r-lifecycle
  - r-rlang
  - r-utf8
  - r-vctrs

tests:
- package_contents:
    lib:
    - R/library/${{ name[2:] }}/libs/${{ name[2:] }}.so

about:
  homepage: https://github.com/r-lib/pillar
  license: GPL-3.0-only
  license_family: GPL3
  summary: Provides 'pillar' and 'colonnade' generics designed for formatting columns of data using the full range of colours provided by modern terminals.

extra:
  recipe-maintainers:
  - IsabelParedes
  - anutosh491
