context:
  name: r-pkgconfig
  version: 2.0.3
  r_base_version: 4.4.1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url:
    - https://cran.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
    - https://cloud.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
  sha256: 330fef440ffeb842a7dcfffc8303743f1feae83e8d6131078b5a44ff11bc3850

build:
  number: 0

requirements:
  build:
  - r-base == ${{ r_base_version }}
  host:
  - r-base == ${{ r_base_version }}
  run:
  - r-base == ${{ r_base_version }}

# tests:
# - package_contents:
#     lib:
#     - R/library/${{ name[2:] }}/libs/${{ name[2:] }}.so

about:
  homepage: https://github.com/r-lib/pkgconfig
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Set configuration options on a per-package basis. Options set by a given package only
    apply to that package, other packages are unaffected.

extra:
  recipe-maintainers:
  - IsabelParedes
  - anutosh491
