context:
  name: r-crayon
  version: 1.5.3
  r_base_version: 4.4.1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url:
    - https://cran.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
    - https://cloud.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
  sha256: 3e74a0685541efb5ea763b92cfd5c859df71c46b0605967a0b5dbb7326e9da69

build:
  number: 0

requirements:
  build:
  - r-base == ${{ r_base_version }}
  host:
  - r-base == ${{ r_base_version }}
  run:
  - r-base == ${{ r_base_version }}

tests:
- package_contents:
    lib:
    - R/library/${{ name[2:] }}/libs/${{ name[2:] }}.so

about:
  homepage: https://github.com/r-lib/crayon#readme
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Colored terminal output on terminals that support 'ANSI' color and highlight codes. It also works in 'Emacs' 'ESS'. 'ANSI' color support is automatically detected. Colors and highlighting can be combined and nested. New styles can also be created easily. This package was inspired by the 'chalk' 'JavaScript' project.

extra:
  recipe-maintainers:
  - IsabelParedes
  - anutosh491
