context:
  version: 1.0.4
  name: r-lifecycle
  r_base_version: 4.4.1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url:
    - https://cran.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
    - https://cloud.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
  sha256: ada4d3c7e84b0c93105e888647c5754219a8334f6e1f82d5afaf83d4855b91cc

build:
  number: 0
  script:
    - $R CMD INSTALL $R_ARGS --no-byte-compile .
    - rm $PREFIX/lib/R/library/grDevices/libs/cairo.so
    - rm $PREFIX/lib/R/library/tcltk/libs/tcltk.so
    # The activation script of cross-r-base copies cairo and tcltk from
    # the build environment.

requirements:
  build:
    - cross-r-base >= ${{ r_base_version }}
    - r-rlang
  host:
    - r-base >= ${{ r_base_version }}
    - r-cli >=3.6.3
    - r-glue
    - r-rlang
  run:
    - r-base >= ${{ r_base_version }}
    - r-cli >=3.6.3
    - r-glue
    - r-rlang

about:
  homepage: https://github.com/r-lib/lifecycle
  repository: https://github.com/r-lib/lifecycle
  license: MIT
  license_family: GPL3
  summary: |
   Manage the life cycle of your exported functions with shared conventions,
   documentation badges, and non-invasive deprecation warnings. The 'lifecycle' package 
   defines four development stages (experimental, maturing, stable, and questioning) and
   three deprecation stages (soft-deprecated, deprecated, and defunct). It makes it easy to
   insert badges corresponding to these stages in your documentation. Usage of deprecated 
   functions are signalled with increasing levels of non-invasive verbosity.

extra:
  recipe-maintainers:
    - IsabelParedes
    - anutosh491