context:
  version: 0.7.6

package:
  name: xeus-lua
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-lua/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9f64a235cb59dccf1c972368145b13198870a8dbaf4311eac4e00af50f3c219b


build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja
  host:
  - lua
  - nlohmann_json
  - xeus-lite >=3.0.0,<4.0
  - xeus >=5.0.0,<6.0
  - xcanvas >=0.5,<5.0
  - xwidgets >=0.28.0,<1.0

tests:
- package_contents:
    files:
    - bin/xlua.wasm
    - bin/xlua.js
    - share/jupyter/kernels/xlua/kernel.json
    - share/jupyter/kernels/xlua/logo-32x32.png
    - share/jupyter/kernels/xlua/logo-64x64.png

about:
  license: BSD-3-Clause
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus-lua
  homepage: https://github.com/jupyter-xeus/xeus-lua
extra:
  recipe-maintainers:
  - DerThorsten
  - martinRenou
  - JohanMabille
