context:
  version: 0.4.0

package:
  name: xeus-nelson
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-nelson/archive/refs/tags/${{ version }}.tar.gz
  sha256: 3d0383aad07afe7c4e17ea4be9929de7bb944c7d68939d41aa435f2fc6a7a510

build:
  number: 1

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja
  host:
  - nelson >=0.3,<0.4
  - nlohmann_json
  - xeus-lite >=3.0.0,<4.0
  - xeus >=5.0.0,<6.0

tests:
- script:
  - test -f $PREFIX/bin/xnelson_wasm.wasm
  - test -f $PREFIX/bin/xnelson_wasm.js

about:
  license: BSD-3-Clause
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus-nelson
  homepage: https://github.com/jupyter-xeus/xeus-nelson
extra:
  recipe-maintainers:
  - DerThorsten
  - martinRenou
  - JohanMabille
